name: Mozilla Observatory Report
on:
  workflow_dispatch: # allow manual trigger
  push:
    branches:
      - main
  schedule:
    - cron: "0 10 * * MON" # Every Monday at 10am
jobs:
  observatory:
    runs-on: ubuntu-latest
    steps:
      - name: Test Observatory
        uses: simonireilly/observatory-github-action@v0.1.3
        id: observatory
        with:
          web_host: https://jamesmcnee.com